# Generated by Django 5.0.9 on 2026-08-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('connectors', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Business Standard', max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, help_text='Vendor-side identifier used to match on sync.', max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('csv', 'CSV import'), ('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('atlassian', 'Atlassian')], default='manual', max_length=40)),
                ('total_seats', models.PositiveIntegerField(default=0, help_text='Seats purchased (the cap).')),
                ('used_seats', models.PositiveIntegerField(default=0, help_text='Seats currently assigned.')),
                ('total_seats_is_synced', models.BooleanField(default=False, help_text='True when the vendor API supplies the purchased-seat count itself.')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per seat per billing period.', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='annual', max_length=20)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_pools', to='catalog.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'ordering': ['application__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, help_text="Last sign-in. Powers 'reclaim idle seats'.", null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='licenses.licensepool')),
            ],
            options={
                'ordering': ['user_email'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pools_created', models.PositiveIntegerField(default=0)),
                ('pools_updated', models.PositiveIntegerField(default=0)),
                ('assignments_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='connectors.connection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='licensepool',
            constraint=models.UniqueConstraint(fields=('organization', 'application', 'name'), name='uniq_pool_name_per_application'),
        ),
        migrations.AddConstraint(
            model_name='licenseassignment',
            constraint=models.UniqueConstraint(fields=('pool', 'user_email'), name='uniq_assignment_per_pool_user'),
        ),
    ]
