# Generated by Django 5.0.9 on 2026-08-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending setup'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_hours', models.PositiveIntegerField(default=6)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'display_name'), name='uniq_connection_per_org_provider_name'),
        ),
    ]
