# Generated by Django 5.0.9 on 2026-08-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('licenses', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('all_pools', 'Every licence pool'), ('application', 'One application'), ('pool', 'One licence pool')], default='all_pools', max_length=20)),
                ('condition', models.CharField(choices=[('utilization_above', 'Utilisation % is above'), ('used_seats_above', 'Used seats are above'), ('available_seats_below', 'Available seats are below'), ('renewal_within_days', 'Renewal is within (days)')], default='utilization_above', max_length=30)),
                ('threshold', models.FloatField(help_text="e.g. 90 for '90% utilised' or '90 seats'.")),
                ('recipients', models.JSONField(default=list, help_text='Email addresses, e.g. ["ops@acme.com", "it@acme.com"]')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Minimum gap between two emails for the same pool + rule.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='catalog.application')),
                ('license_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='licenses.licensepool')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('observed_value', models.FloatField(default=0)),
                ('message', models.TextField()),
                ('recipients', models.JSONField(default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('license_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='licenses.licensepool')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
